#!/bin/bash
echo "Sverdlova-1:"
ssh root@192.168.0.1 "iw dev ap scan | grep \"primary channel\" | grep \"\b1\b\|\b6\b\|\b11\b\" | sort -V | uniq -c"
echo "Sverdlova-2:"
ssh root@192.168.0.2 "iw dev ap scan | grep \"primary channel\" | grep \"\b1\b\|\b6\b\|\b11\b\" | sort -V | uniq -c"
echo "Danilevskii-1:"
ssh root@192.168.1.1 "iw dev ap scan | grep \"primary channel\" | grep \"\b1\b\|\b6\b\|\b11\b\" | sort -V | uniq -c"
echo "Danilevskii-2:"
ssh root@192.168.1.2 "iw dev ap scan | grep \"primary channel\" | grep \"\b1\b\|\b6\b\|\b11\b\" | sort -V | uniq -c"
echo "Danilevskii-3:"
ssh root@192.168.1.3 "iw dev ap scan | grep \"primary channel\" | grep \"\b1\b\|\b6\b\|\b11\b\" | sort -V | uniq -c"
echo "Danilevskii-4:"
ssh root@192.168.1.4 "iw dev ap scan | grep \"primary channel\" | grep \"\b1\b\|\b6\b\|\b11\b\" | sort -V | uniq -c"
echo "Spb-1:"
ssh root@192.168.2.1 "iw dev wlan1 scan | grep \"primary channel\" | grep \"\b1\b\|\b6\b\|\b11\b\" | sort -V | uniq -c"

